//import { create } from "core-js/core/object";

// seeders/xxxx-tariffs-seeder.js
export async function up(queryInterface, Sequelize) {
  await queryInterface.bulkDelete("Tariffs", null, {});
  await queryInterface.bulkInsert("Tariffs", [
    {
      key: "truck.block12_price",
      name: "Truck 12h block price",
      entityType: "truck",
      value: 5000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Price for 12-hour block for trucks",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "boat.block12_price",
      name: "Boat 12h block price",
      entityType: "boat",
      value: 5000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Price for 12-hour block for boats",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "vessel.first3_days_price",
      name: "Vessel first 3 days price",
      entityType: "vessel",
      value: 210000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Price for first 3 days for vessels",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "vessel.daily_extra",
      name: "Vessel extra day price",
      entityType: "vessel",
      value: 28000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Price for extra day for vessels",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "cargo.import_multiplier",
      name: "Cargo import multiplier",
      entityType: "cargo",
      value: 2,
      unit: "multiplier",
      effectiveFrom: new Date(),
      description: "Multiplier for cargo import",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "cargo.export_multiplier",
      name: "Cargo export multiplier",
      entityType: "cargo",
      value: 0.4,
      unit: "multiplier",
      effectiveFrom: new Date(),
      description: "Multiplier for cargo export",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "storage.grace_days",
      name: "Storage grace days",
      entityType: "storage",
      value: 14,
      unit: "days",
      effectiveFrom: new Date(),
      description: "Grace days for storage",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "storage.multiplier_15_30",
      name: "Storage multiplier 15-30",
      entityType: "storage",
      value: 0.6,
      unit: "multiplier",
      effectiveFrom: new Date(),
      description: "Multiplier for storage 15-30 days",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "storage.multiplier_31_plus",
      name: "Storage multiplier 31+",
      entityType: "storage",
      value: 1.2,
      unit: "multiplier",
      effectiveFrom: new Date(),
      description: "Multiplier for storage 31+ days",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "facility.petrol_station",
      name: "Petrol station monthly",
      entityType: "facility",
      value: 250000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Monthly fee for petrol station",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "facility.office",
      name: "Office monthly",
      entityType: "facility",
      value: 120000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Monthly fee for office",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "facility.restaurant",
      name: "Restaurant monthly",
      entityType: "facility",
      value: 100000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Monthly fee for restaurant",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "facility.garage",
      name: "Garage monthly",
      entityType: "facility",
      value: 50000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Monthly fee for garage",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      key: "facility.unpaved_space",
      name: "Unpaved space monthly",
      entityType: "facility",
      value: 50000,
      unit: "RWF",
      effectiveFrom: new Date(),
      description: "Monthly fee for unpaved space",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
}

export async function down(queryInterface, Sequelize) {
  await queryInterface.bulkDelete("Tariffs", null, {});
}
